Added UML Diagram
UdL-EPS-SoftArch/webmemory-api pull request #6
Opened 2019-03-07 15:57 UTC by tarikcosovic

2019-03-08 07:53 UTC, jmgimeno requested changes
Your UML diagram uses only extension relations --|> but you should use --> or --|>, the first one for unidirectional associations and the second one for extension.

2019-03-14 15:50 UTC, jmgimeno requested changes
It seems strange that in a memory game there is no Card class, doesn't it?

2019-04-09 15:38 UTC, tarikcosovic commented
We are going to use numbers and for that reason we don't really need a card class

2019-04-10 12:07 UTC, jmgimeno approved these changes

2019-04-10 12:07 UTC, merged